### ISSUE TITLE
Latest plugin version doesn't work on 4.27.2 ... previous ones did....

### ISSUE THREAD

**Issue by ImagineTheGames** [getsentry/sentry-unreal#530]
What problem could Sentry solve that it doesn't?

It would be nice to continue supporting 4.27 since a lot of released games are version locked to this release....

**Comment by tustanivsky** [comment]
Thank you for raising this - we'd definitely like to preserve plugin compatibility with some older engine versions.

**Comment by tustanivsky** [comment]
@ImagineTheGames Can you elaborate on the issue you're facing when using the latest plugin version in UE 4.27? I've tested it on my side and besides a minor compilation error caused by some new unreleased features (which of course will be addressed separately) everything seems to work as expected.

**Comment by bitsandfoxes** [comment]
@ImagineTheGames can you provide us with some additional information/logs as to what does not work for you specifically?

**Comment by ImagineTheGames** [comment]
Just saw this sorry. will gather all info ASAP;...

**Comment by ImagineTheGames** [comment]
I can't find any issues (compiled both linux & windows targets just fine). Must have been a fluke on my end. Sorry.

**Comment by ImagineTheGames** [comment]
I found the cause of this issue:
USentrySubsystem* SentrySubsystem = GameInstance->GetSubsystem<USentrySubsystem>();

this code used to compile previously but now with the whole subsystem update it doesn't, what would be the correct way to reference it now?

its failing on the static_assert shown below

template<typename TBaseType>
class FSubsystemCollection : public FSubsystemCollectionBase
{
public:
	/** Get a Subsystem by type */
	template <typename TSubsystemClass>
	TSubsystemClass* GetSubsystem(const TSubclassOf<TSubsystemClass>& SubsystemClass) const
	{

its failing to compile on this below static_assert:
		static_assert(TIsDerivedFrom<TSubsystemClass, TBaseType>::IsDerived, "TSubsystemClass must be derived from TBaseType");

		// A static cast is safe here because we know SubsystemClass derives from TSubsystemClass if it is not null
		return static_cast<TSubsystemClass*>(GetSubsystemInternal(SubsystemClass));
	}

**Comment by ImagineTheGames** [comment]
solved... it just needs to be changed to
USentrySubsystem* SentrySubsystem = Engine->GetEngineSubsystem<USentrySubsystem>();
since its no longer a game subsystem but engine subsystem
